### PR TITLE
fix(instance): use args zone on vpc call

### LINKED ISSUE #1457: Private Nics on server get does not respect zone args
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by Sh4d1**
Signed-off-by: Patrik Cyvoct <pcyvoct@scaleway.com>

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #1457

### CODE REVIEW

File: internal/namespaces/instance/v1/custom_server.go [hunk 1]
```diff
@@ -354,6 +355,7 @@ func serverGetBuilder(c *core.Command) *core.Command {
 		for _, nic := range getServerResp.Server.PrivateNics {
 			pn, err := vpcAPI.GetPrivateNetwork(&vpc.GetPrivateNetworkRequest{
 				PrivateNetworkID: nic.PrivateNetworkID,
+				Zone:             args.Zone,
```
Comment (jerome-quere) [inline internal/namespaces/instance/v1/custom_server.go:358]: IMHO: You should use getServerResp.Zone

**Review by jerome-quere — CHANGES_REQUESTED** [review]

File: internal/namespaces/instance/v1/custom_server.go (hunk 1 above)
Comment (Sh4d1) [reply internal/namespaces/instance/v1/custom_server.go:358]: I was torn between the two options :sweat_smile: i'll update

**Review by QuentinBrosse — APPROVED** [review]
LGTM

**Review by jerome-quere — APPROVED** [review]
