### PR TITLE
fix(core): add disableCheckVersion option to commands

### LINKED ISSUE #1899: Disable updates check when launching the terminal
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When launching the terminal, it takes long time before it launches because scw is doing a request to check if a new release of scw is available. 

### How I imagine scw could expose this functionality

Please expose a way to disable this startup check
Also, maybe you can do this check at another time, maybe when the command has finish execution. Like `npm` does.

### PR DESCRIPTION
**Pull request by Codelax**
Fix #1899

### CODE REVIEW

File: internal/core/build_info.go [hunk 1]
```diff
@@ -57,7 +57,9 @@ func (b *BuildInfo) GetUserAgent() string {
 }
 
 func (b *BuildInfo) checkVersion(ctx context.Context) {
-	if !b.IsRelease() || ExtractEnv(ctx, scwDisableCheckVersionEnv) == "true" {
+	cmd := extractMeta(ctx).command
```
Comment (remyleone) [inline internal/core/build_info.go:60]: Could you add some documentation in the configuration file (cli.yaml) as well?

**Review by quantumsheep — APPROVED** [review]

File: internal/core/build_info.go (hunk 1 above)
Comment (Codelax) [reply internal/core/build_info.go:60]: Some documentation ? It is not configurable in `cli.yaml`.
