### PR TITLE
fix/shell-display-how-to-quit

### LINKED ISSUE #3621: shell: display how to quit
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To quit shell mode (`scw shell`) you must use Ctrl-D to close stdin. We should display an help when starting the shell.
`scw instance server console` can be used as a reference

### PR DESCRIPTION
**Pull request by Laure-di**
close #3621

### CODE REVIEW

**Comment by Codelax** [comment]
There is an issue using this PR's branch:
```
> scw -h
 - Type Ctrl+d to quit.
USAGE:
  scw <command>

AVAILABLE COMMANDS:
...
```

File: internal/namespaces/shell/shell.go [hunk 1]
```diff
@@ -22,6 +23,7 @@ func shellCommand() *core.Command {
 		AllowAnonymousClient: false,
 		ArgsType:             reflect.TypeOf(args.RawArgs{}),
 		Run: func(ctx context.Context, argsI interface{}) (interface{}, error) {
+			fmt.Println(" - Type Ctrl+d to quit.")
```
Comment (Codelax) [inline internal/namespaces/shell/shell.go:26]: There is no need for both prints. This one can go as this is never called
