### PR TITLE
fix(inference): fix endpoint nil pointer create deployment

### LINKED ISSUE #3921: inference invalid memory address or nil pointer dereference
scw inference deployment create model-name=meta/llama-3-8b-instruct:bf16 node-type=L4 endpoints.0.is-public=true
---------------------------------------------------------------------------------------
An error occurred, we are sorry, please consider opening a ticket on github using: 'scw feedback bug'
Give us as many details as possible so we can reproduce the error and fix it.
---------------------------------------------------------------------------------------
runtime error: invalid memory address or nil pointer dereference
stacktrace from panic:
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x5e
main.cleanup(0xc00025b1f0)
	/Users/lauremasson/Documents/devtools/scaleway-cli/cmd/scw/main.go:42 +0xdd
panic({0xf3ffc40?, 0x103b3a70?})
	/usr/local/opt/go/libexec/src/runtime/panic.go:770 +0x132
github.com/scaleway/scaleway-cli/v2/internal/namespaces/inference/v1beta1.deploymentCreateBuilder.func2({0xf6b1eb0, 0xc0006b0120}, {0xf2ee1c0?, 0xc00071f340?}, 0xc0004e16e0)
	/Users/lauremasson/Documents/devtools/scaleway-cli/internal/namespaces/inference/v1beta1/custom_deployment.go:102 +0x209
github.com/scaleway/scaleway-cli/v2/internal/core.run.CombineCommandInterceptor.func3.1({0xf6b1eb0?, 0xc0006b0120?}, {0x0?, 0x0?})
	/Users/lauremasson/Documents/devtools/scaleway-cli/internal/core/command_interceptor.go:30 +0x2e
github.com/scaleway/scaleway-cli/v2/internal/core.sdkStdTypeInterceptor({0xf6b1eb0, 0xc0006b0120}, {0xf2ee1c0?, 0xc00071f340?}, 0x0?)
	/Users/lauremasson/Documents/devtools/scaleway-cli/internal/core/command_interceptor.go:123 +0x2f
github.com/scaleway/scaleway-cli/v2/internal/core.run.CombineCommandInterceptor.func3.1({0xf6b1eb0?, 0xc0006b0120?}, {0xdd05d59?, 0x0?})
	/Users/lauremasson/Documents/devtools/scaleway-cli/internal/core/command_interceptor.go:30 +0x2e
github.com/scaleway/scaleway-cli/v2/internal/core.sdkStdErrorInterceptor({0xf6b1eb0?, 0xc0006b0120?}, {0xf2ee1c0?, 0xc00071f340?}, 0x28?)
	/Users/lauremasson/Documents/devtools/scaleway-cli/internal/core/command_interceptor.go:39 +0x46
github.com/scaleway/scaleway-cli/v2/internal/core.run.CombineCommandInterceptor.func3({0xf6b1eb0, 0xc0006b0120}, {0xf2ee1c0, 0xc00071f340}, 0xc0001959b0)
	/Users/lauremasson/Documents/devtools/scaleway-cli/internal/core/command_interceptor.go:29 +0xb9
github.com/scaleway/scaleway-cli/v2/internal/core.run.CombineCommandInterceptor.func3({0xf6b1eb0, 0xc0006b0120}, {0xf2ee1c0, 0xc00071f340}, 0xc0004e16e0)
	/Users/lauremasson/Documents/devtools/scaleway-cli/internal/core/command_interceptor.go:29 +0xb9
github.com/scaleway/scaleway-cli/v2/internal/core.run({0xf6b1eb0, 0xc0006b0120}, 0xc00065c008, 0xc0004e2420, {0xc00069e120, 0x6, 0x6})
	/Users/lauremasson/Documents/devtools/scaleway-cli/internal/core/cobra_utils.go:172 +0x3dc
github.com/scaleway/scaleway-cli/v2/internal/core.(*cobraBuilder).hydrateCobra.cobraRun.func3(0xc00065c008, {0xc0000b6a50, 0x3, 0x3})
	/Users/lauremasson/Documents/devtools/scaleway-cli/internal/core/cobra_utils.go:46 +0x6ad
github.com/spf13/cobra.(*Command).execute(0xc00065c008, {0xc0002e9e00, 0x3, 0x3})
	/Users/lauremasson/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc00028f808)
	/Users/lauremasson/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/lauremasson/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/scaleway/scaleway-cli/v2/internal/core.Bootstrap(0xc000551e78)
	/Users/lauremasson/Documents/devtools/scaleway-cli/internal/core/bootstrap.go:263 +0x12b9
main.main()
	/Users/lauremasson/Documents/devtools/scaleway-cli/cmd/scw/main.go:74 +0x34f

### PR DESCRIPTION
**Pull request by Laure-di**
close #3921

### CODE REVIEW

File: internal/namespaces/inference/v1beta1/custom_deployment.go [hunk 1]
```diff
@@ -96,7 +96,7 @@ func deploymentCreateBuilder(c *core.Command) *core.Command {
 				publicEndpoint = nil
 			}
 			privateNetwork := &inference.EndpointSpecPrivateNetwork{}
-			if endpoint.EndpointSpec == nil {
+			if endpoint.EndpointSpec.PrivateNetwork == nil {
```
Comment (remyleone) [inline internal/namespaces/inference/v1beta1/custom_deployment.go:99]: What if `endpoint.EndpointSpec` is already nil?

Comment (Laure-di) [reply internal/namespaces/inference/v1beta1/custom_deployment.go:99]: It creates a public endpoint.

**Review by remyleone — APPROVED** [review]
