### PR TITLE
fix(shell): arg doc when using positional arguments

### LINKED ISSUE #2508: shell: completion description is missing with positional arguments
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

image

```
lb backend update 18b068f7-4ad8-4fb7-8101-f01e399cdb29 forward-port-algorith
```

### Expected Behavior

Field should be documented

### Actual Behavior

Field description is "command not found"

### PR DESCRIPTION
**Pull request by Codelax**
Fix #2508 
Positional args are now documented, and classic args got their doc back when using a positional argument

### CODE REVIEW

File: internal/core/shell.go [hunk 1]
```diff
@@ -133,23 +148,29 @@ func getCommand(meta *meta, args []string, suggest string) *Command {
...
-	return ""
+	if argIsPositional(command, suggest) {
+		option := command.ArgSpecs.GetPositionalArg()
+		if option != nil {
+			return option.Short
+		}
+		return ""
+	}
+
+	// Should be a command, juste use command short
```
Comment (Codelax) [inline internal/core/shell.go:172]:
```suggestion
	// Should be a command, just use command short
```

**Review by remyleone — APPROVED** [review]
