### PR TITLE
fix(apple-silicon): improve vizualization compatible server types

### LINKED ISSUE #3824: Improve vizualisation CompatibleServerTypes
scw apple-silicon os get <id>

### PR DESCRIPTION
**Pull request by Laure-di**
close #3824

### CODE REVIEW

File: internal/namespaces/applesilicon/v1alpha1/custom_os.go [hunk 1]
```diff
@@ -0,0 +1,22 @@
+package applesilicon
```
Comment (remyleone) [inline internal/namespaces/applesilicon/v1alpha1/custom_os.go:1]: What golden is modified by this function? Could you add a test for it?

**Review by remyleone — CHANGES_REQUESTED** [review]

**Review by remyleone — APPROVED** [review]
