### PR TITLE
fix(baremetal): better rendering get offer

### LINKED ISSUE #3665: baremetal add better vizualisation get offer
Add better vizualisation
scw baremetal offer get offer-id=
section for options, memories, cpu

### PR DESCRIPTION
**Pull request by Laure-di**
close #3665

### CODE REVIEW

File: internal/namespaces/baremetal/v1/custom_offer_test.go [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+	"testing"
+
+	"github.com/scaleway/scaleway-cli/v2/internal/core"
+)
+
+func Test_baremetalGetOffer(t *testing.T) {
+	offerID := "c5853302-63e4-40c7-a711-4a91629565c8"
+	t.Run("Simple", core.Test(&core.TestConfig{
+		Commands: GetCommands(),
+		Cmd:      "scw baremetal offer get offer-id=" + offerID,
```
Comment (remyleone) [inline internal/namespaces/baremetal/v1/custom_offer_test.go:13]: Could you make offer-id positional ?

Comment (Laure-di) [reply internal/namespaces/baremetal/v1/custom_offer_test.go:13]: Yes, I can. Do we really need the offerID as an argument? Why not use the name of the offer instead? I don't see any cases where this would be a breaking change

File: internal/namespaces/baremetal/v1/testdata/test-baremetal-get-offer-simple.golden [hunk 2]
```diff
@@ -0,0 +1,12 @@
+🎲🎲🎲 EXIT CODE: 1 🎲🎲🎲
+🟥🟥🟥 STDERR️️ 🟥🟥🟥️
+Unknown argument 'c5853302-63e4-40c7-a711-4a91629565c8'
```
[the remark this answers is not in the document]
Comment (Laure-di) [reply internal/namespaces/baremetal/v1/testdata/test-baremetal-get-offer-simple.golden:3]: Oups shame on me, I know where the issue is

File: internal/namespaces/baremetal/v1/testdata/test-baremetal-get-offer-simple.golden [hunk 3]
```diff
@@ -0,0 +1,183 @@
...
+Stock               available
+Bandwidth           1000000000
+CommercialRange     lithium
+PricePerHour        € 0.213
+Enable              true
+QuotaName           EM_L105X_SATA
+SubscriptionPeriod  hourly
+OperationPath       -
+Fee                 € 0.00
+PrivateBandwidth    1000000000
```
Comment (Codelax) [inline internal/namespaces/baremetal/v1/testdata/test-baremetal-get-offer-simple.golden:14]: Can we improve bandwidth to have a readable format ?

Comment (Laure-di) [reply internal/namespaces/baremetal/v1/testdata/test-baremetal-get-offer-simple.golden]: Change to Mbit after discussion

**Review by remyleone — APPROVED** [review]
